#!/bin/bash

function upgrade {
	echo -e "
apt upgrade is unsafe on rolling release distributions.

using apt full-upgrade instead

use apt upgrade --force to override


"
	/usr/bin/apt update
	/usr/bin/apt full-upgrade
}

case $1 in
	upgrade)
		upgrade
		case $2 in --force)
			/usr/bin/apt upgrade;;
		esac
		exit
	;;
	dup|up|u)
		upgrade
		exit
	;;
	refresh)
		/usr/bin/apt update
		exit
	;;
	in)
		/usr/bin/apt install ${@:2}
		exit
	;;
	rm)
		/usr/bin/apt remove ${@:2}
		exit
	;;
	list-updates|lu)
		/usr/bin/apt list --upgradable
		exit
	;;
	se)
		/usr/bin/apt search ${@:2}
		exit
	;;
	po)
		/usr/bin/apt policy ${@:2}
		exit
	;;
	sh)
		/usr/bin/apt show ${@:2}
		exit
	;;
	
esac

/usr/bin/apt $@
