#!/bin/bash
set -e


#update xapian index

if [ -x "/usr/sbin/update-xapian-index" ]
then
	update-apt-xapian-index -vf
fi



#install parrot repositories if missing

if ! [ -e "/etc/apt/sources.list.d/parrot.list" ]
then
	parrot-mirror-selector euro3 stable nonfree
fi

if [ -e "/etc/parrot.testing" ]
then
	parrot-mirror-selector euro3 testing nonfree
fi

if ! [ -e "/etc/apt/sources.list" ]
then
	echo /etc/apt/sources.list.parrot > /etc/apt/sources.list
fi
